language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov

services:
  - postgresql

env:
  global:
    - SECRET='sddsdwejernefnbfbhejwjfjfjwjnd'

before_script:
  - psql -c 'CREATE DATABASE test_ireporter' -U postgres


script:
  - pytest
  - pytest --cov=./
  - coverage report

after_success:
  - coveralls
